# Generated by Django 5.1 on 2024-09-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('passenger', 'Passenger'), ('driver', 'Taxi Driver')], default='passenger', max_length=10),
        ),
    ]
