<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-09-26 16:39
=======
# Generated by Django 5.1 on 2024-09-26 14:55
>>>>>>> a223dcd8209e2b5e8efb52f07b4565be1d33d095

from django.db import migrations, models


class Migration(migrations.Migration):
<<<<<<< HEAD
    dependencies = [
        ("login", "0001_initial"),
=======

    dependencies = [
        ('login', '0001_initial'),
>>>>>>> a223dcd8209e2b5e8efb52f07b4565be1d33d095
    ]

    operations = [
        migrations.AddField(
<<<<<<< HEAD
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("passenger", "ผู้ใช้บริการ"), ("driver", "คนขับ Taxi")],
                default="passenger",
                max_length=10,
            ),
=======
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('passenger', 'Passenger'), ('driver', 'Taxi Driver')], default='passenger', max_length=10),
>>>>>>> a223dcd8209e2b5e8efb52f07b4565be1d33d095
        ),
    ]
