# Generated by Django 5.0.6 on 2024-09-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("passenger", "ผู้ใช้บริการ"), ("driver", "คนขับ Taxi")],
                default="passenger",
                max_length=10,
            ),
        ),
    ]
