# Generated by Django 5.1 on 2024-09-26 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxidriver',
            name='car_plate',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='taxidriver',
            name='license_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='taxidriver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='login_taxidriver', to=settings.AUTH_USER_MODEL),
        ),
    ]
