# Generated by Django 5.1 on 2024-09-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_taxidriver_car_plate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('passenger', 'ผู้โดยสาร'), ('driver', 'คนขับ')], default='passenger', max_length=10),
        ),
    ]
