# Generated by Django 5.1 on 2024-09-26 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_taxidriver_alter_ride_driver'),
        ('login', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaxiDriver',
        ),
    ]
