# Generated by Django 5.1 on 2024-09-29 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_location_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxidriver',
            name='current_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.location'),
        ),
    ]
